In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import roc_curve, auc, confusion_matrix, classification_report,accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
%matplotlib inline

In [8]:
data = pd.read_csv("DataM.csv")
data.fillna(0, inplace=True)
del data['ID']
del data['ID_litter']
del data['group']
del data['IgGJ2']
del data['AgeD2']
del data['Min1inflcr']
del data['Size']
del data['sex']
data.head()

litt_size  TPI  Diarr  Age_D1  hospit  InfCroissPed  InfCroiss4  \
0          5  0.0      1    28.0       1             1           1   
1          5  0.0      1    29.0       0             1           1   
2          5  0.0      0     0.0       0             1           0   
3          5  0.0      1    54.0       1             1           0   
4          5  0.0      1    52.0       1             1           0   

   InfCroiss5  InfCroiss6  InfCroiss7  ...  TRD48  TRD49  TRD50  TRD51  TRD52  \
0           0           0         0.0  ...   38.4   38.2   38.4   38.9   38.7   
1           0           0         0.0  ...   38.4   37.4   37.8   39.1   38.1   
2           1           0         0.0  ...   38.2   38.4   38.1   38.8   39.1   
3           1           0         0.0  ...   38.4   38.4   38.4   38.9   38.3   
4           1           0         0.0  ...   38.3   38.7   38.6   39.1   37.4   

   TRD53  TRD54  TRD55  TRD56  Died  
0   38.5   38.7   39.0   39.0     1  
1   38.7   37.7   37.9   38.3     0  
2   37.4   38.0   38.2   37.6     0  
3   38.5   38.6   38.0   38.0     0  
4   37.4   37.4   37.4   37.4     0  

[5 rows x 48 columns]

In [9]:
array = data.values
array[0]

array([ 5. ,  0. ,  1. , 28. ,  1. ,  1. ,  1. ,  0. ,  0. ,  0. ,  0. ,
       37.5, 37.5, 37.5, 37.8, 37.7, 37.8, 37.3, 37.9, 37.5, 37.7, 37.8,
       38.3, 38. , 38.1, 37.9, 38. , 37.8, 38.2, 38. , 38.5, 38.3, 37.7,
       38.4, 38.4, 38.8, 38.5, 38.4, 38.4, 38.2, 38.4, 38.9, 38.7, 38.5,
       38.7, 39. , 39. ,  1. ])

In [37]:
X = array[:,0:47]
Y = array[:,47]

In [11]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [12]:
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(X, Y)
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)
print(features[0:5,:])

[1.378e-01 5.939e-02 1.346e+01 7.314e+02 1.858e+01 7.511e-02 4.723e-03
 1.270e+00 2.621e-01 1.786e+00 5.346e-01 2.041e-04 3.224e-06 7.829e-04
 4.113e-04 3.949e-04 3.055e-03 7.484e-04 4.582e-05 2.066e-05 1.172e-03
 4.601e-03 3.416e-03 7.010e-04 8.569e-04 2.641e-02 2.566e-03 9.591e-03
 7.562e-03 1.192e-02 1.735e-02 1.906e-05 7.803e-04 1.538e-03 4.170e-04
 2.754e-02 6.943e-03 1.753e-03 5.599e-03 7.870e-03 5.474e-03 2.283e-02
 8.609e-03 1.878e-04 3.761e-03 4.475e-03 1.022e-02]
[[ 1. 28.  1.  0.]
 [ 1. 29.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 1. 54.  1.  0.]
 [ 1. 52.  1.  0.]]


### Wrapper

In [13]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [46]:
model = LogisticRegression()
rfe = RFE(model, 10)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

I

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Num Features: 10
Selected Features: [False False False False  True False False  True False False  True False
 False False False False False  True False  True False False False False
 False  True  True  True False False False False False False False  True
 False False False False  True False False False False False False]
Feature Ranking: [22 21 36 31  1 15 35  1 24  8  1  2  6 20 38 19 34  1 12  1 17  7 23 27
  5  1  1  1 29 13  3 37 14 30  4  1 25 33 32 11  1 28 16  9 18 26 10]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [44]:
from colorama import Fore
from termcolor import colored

print("Les 10 caractéristiques les mieux classées :\n")
for idx,column in enumerate(data.columns):
    if(idx == 4 or idx==7 or idx == 25 or idx==26 or idx==35):
        print(Fore.BLUE, idx,column)
print(Fore.BLACK, "-------------------")
for idx,column in enumerate(data.columns):     
    if(idx == 10 or idx==17 or idx == 19 or idx==27 or idx==40):
        print(Fore.RED, idx,column)

Les 10 caractéristiques les mieux classées :

 4 hospit
 7 InfCroiss5
 25 TRD35
 26 TRD36
 35 TRD45
 -------------------
 10 InfCroiss8
 17 TRD27
 19 TRD29
 27 TRD37
 40 TRD50


## Test sur la diarrée 

In [68]:
dataD = pd.read_csv("DataD.csv")
dataD.fillna(0, inplace=True)
del dataD['ID']
del dataD['ID_litter']
del dataD['group']
del dataD['IgGJ2']
del dataD['AgeD2']
del dataD['Min1inflcr']
del dataD['Size']
del dataD['sex']
dataD.head()

litt_size  TPI  Died  Age_D1  hospit  InfCroissPed  InfCroiss4  InfCroiss5  \
0          5  0.0     1    28.0       1           0.0           1           0   
1          5  0.0     0    29.0       0           0.0           1           0   
2          5  0.0     0     0.0       0           0.0           0           1   
3          5  0.0     0    54.0       1           0.0           0           1   
4          5  0.0     0    52.0       1           1.0           0           1   

   InfCroiss6  InfCroiss7  ...  TRD48  TRD49  TRD50  TRD51  TRD52  TRD53  \
0           0         0.0  ...   38.4   38.2   38.4   38.9   38.7   38.5   
1           0         0.0  ...   38.4   37.4   37.8   39.1   38.1   38.7   
2           0         0.0  ...   38.2   38.4   38.1   38.8   39.1   37.4   
3           0         0.0  ...   38.4   38.4   38.4   38.9   38.3   38.5   
4           0         0.0  ...   38.3   38.7   38.6   39.1   37.4    0.0   

   TRD54  TRD55  TRD56  Diarr  
0   38.7   39.0    0.0      1  
1   37.7   37.9   38.3      1  
2   38.0   38.2   37.6      0  
3   38.6   38.0    0.0      1  
4    0.0    0.0    0.0      1  

[5 rows x 48 columns]

In [69]:
arrayD = dataD.values
X = arrayD[:,0:47]
Y = arrayD[:,47]

In [70]:
model = LogisticRegression()
rfe = RFE(model, 10)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

I

Num Features: 10
Selected Features: [ True False False  True False False False False False False False False
 False  True False False  True False False False False False False False
 False False False False False False False False False False False False
 False False  True False False False  True  True  True  True  True]
Feature Ranking: [ 1 37 31  1 25 27  6 23 13 20 19 33 24  1 26 30  1 16 29  2  8 34  9 18
 21 28 38  5 14  3 17  4 11 15 32 35 36 22  1 10  7 12  1  1  1  1  1]


In [71]:
from colorama import Fore
from termcolor import colored
 
print("Les 10 caractéristiques les mieux classées :\n")
for idx,column in enumerate(dataD.columns):
    if(idx == 3 or idx==38 or idx == 44 or idx==45 or idx==46):
        print(Fore.BLUE, idx,column)
print(Fore.BLACK, "-------------------")
for idx,column in enumerate(dataD.columns):     
    if(idx == 0 or idx==13 or idx == 16 or idx==42 or idx==43):
        print(Fore.RED, idx,column)

Les 10 caractéristiques les mieux classées :

 3 Age_D1
 38 TRD48
 44 TRD54
 45 TRD55
 46 TRD56
 -------------------
 0 litt_size
 13 TRD23
 16 TRD26
 42 TRD52
 43 TRD53


## Test avec l'hospitalisation 

In [72]:
dataH = pd.read_csv("DataH.csv")
dataH.fillna(0, inplace=True)
del dataH['ID']
del dataH['ID_litter']
del dataH['group']
del dataH['IgGJ2']
del dataH['AgeD2']
del dataH['Min1inflcr']
del dataH['Size']
del dataH['sex']
dataH.head()

litt_size  TPI  Died  Age_D1  Diarr  InfCroissPed  InfCroiss4  InfCroiss5  \
0          5  0.0     1    28.0      1           0.0           1           0   
1          5  0.0     0    29.0      1           0.0           1           0   
2          5  0.0     0     0.0      0           0.0           0           1   
3          5  0.0     0    54.0      1           0.0           0           1   
4          5  0.0     0    52.0      1           1.0           0           1   

   InfCroiss6  InfCroiss7  ...  TRD48  TRD49  TRD50  TRD51  TRD52  TRD53  \
0           0         0.0  ...   38.4   38.2   38.4   38.9   38.7   38.5   
1           0         0.0  ...   38.4   37.4   37.8   39.1   38.1   38.7   
2           0         0.0  ...   38.2   38.4   38.1   38.8   39.1   37.4   
3           0         0.0  ...   38.4   38.4   38.4   38.9   38.3   38.5   
4           0         0.0  ...   38.3   38.7   38.6   39.1   37.4    0.0   

   TRD54  TRD55  TRD56  hospit  
0   38.7   39.0    0.0       1  
1   37.7   37.9   38.3       0  
2   38.0   38.2   37.6       0  
3   38.6   38.0    0.0       1  
4    0.0    0.0    0.0       1  

[5 rows x 48 columns]

In [73]:
arrayH = dataH.values
X = arrayH[:,0:47]
Y = arrayH[:,47]

In [74]:
model = LogisticRegression()
rfe = RFE(model, 10)
fit = rfe.fit(X, Y)
print("Num Features: %s" % (fit.n_features_))
print("Selected Features: %s" % (fit.support_))
print("Feature Ranking: %s" % (fit.ranking_))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=10 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

I

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Num Features: 10
Selected Features: [False False  True False  True  True  True False  True False False False
 False False  True  True False False False False False  True False False
 False False False False False False False False False False  True False
 False False  True False False False False False False False False]
Feature Ranking: [12  3  1 24  1  1  1 18  1  7 10 15  6 31  1  1 16 14 11  9 13  1  4 30
  2 20 21 22 26 38 28 19  8 37  1 25 29 34  1 17  5 32 35 36 33 27 23]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [75]:
from colorama import Fore
from termcolor import colored

print("Les 10 caractéristiques les mieux classées :\n")
for idx,column in enumerate(dataH.columns):
    if(idx==2 or idx==4 or idx==5 or idx==14 or idx==21):
        print(Fore.BLUE, idx,column)
print(Fore.BLACK, "-------------------")
for idx,column in enumerate(dataH.columns):     
    if(idx == 6 or idx==8 or idx == 15 or idx==34 or idx==38):
        print(Fore.RED, idx,column)


Les 10 caractéristiques les mieux classées :

 2 Died
 4 Diarr
 5 InfCroissPed
 14 TRD24
 21 TRD31
 -------------------
 6 InfCroiss4
 8 InfCroiss6
 15 TRD25
 34 TRD44
 38 TRD48
